// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: proto/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Signature string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventEnvelope_NewPromotion
	//	*EventEnvelope_Vote
	//	*EventEnvelope_PromotionPublished
	Payload       isEventEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EventEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventEnvelope) GetPayload() isEventEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetNewPromotion() *NewPromotionEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_NewPromotion); ok {
			return x.NewPromotion
		}
	}
	return nil
}

func (x *EventEnvelope) GetVote() *VoteEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *EventEnvelope) GetPromotionPublished() *PromotionPublishedEvent {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_PromotionPublished); ok {
			return x.PromotionPublished
		}
	}
	return nil
}

type isEventEnvelope_Payload interface {
	isEventEnvelope_Payload()
}

type EventEnvelope_NewPromotion struct {
	NewPromotion *NewPromotionEvent `protobuf:"bytes,3,opt,name=new_promotion,json=newPromotion,proto3,oneof"`
}

type EventEnvelope_Vote struct {
	Vote *VoteEvent `protobuf:"bytes,4,opt,name=vote,proto3,oneof"`
}

type EventEnvelope_PromotionPublished struct {
	PromotionPublished *PromotionPublishedEvent `protobuf:"bytes,5,opt,name=promotion_published,json=promotionPublished,proto3,oneof"`
}

func (*EventEnvelope_NewPromotion) isEventEnvelope_Payload() {}

func (*EventEnvelope_Vote) isEventEnvelope_Payload() {}

func (*EventEnvelope_PromotionPublished) isEventEnvelope_Payload() {}

type NewPromotionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   string                 `protobuf:"bytes,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPromotionEvent) Reset() {
	*x = NewPromotionEvent{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPromotionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPromotionEvent) ProtoMessage() {}

func (x *NewPromotionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPromotionEvent.ProtoReflect.Descriptor instead.
func (*NewPromotionEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *NewPromotionEvent) GetPromotionId() string {
	if x != nil {
		return x.PromotionId
	}
	return ""
}

func (x *NewPromotionEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NewPromotionEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type VoteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   string                 `protobuf:"bytes,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	VoteValue     int32                  `protobuf:"varint,2,opt,name=vote_value,json=voteValue,proto3" json:"vote_value,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteEvent) Reset() {
	*x = VoteEvent{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteEvent) ProtoMessage() {}

func (x *VoteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteEvent.ProtoReflect.Descriptor instead.
func (*VoteEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *VoteEvent) GetPromotionId() string {
	if x != nil {
		return x.PromotionId
	}
	return ""
}

func (x *VoteEvent) GetVoteValue() int32 {
	if x != nil {
		return x.VoteValue
	}
	return 0
}

func (x *VoteEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VoteEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PromotionPublishedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   string                 `protobuf:"bytes,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionPublishedEvent) Reset() {
	*x = PromotionPublishedEvent{}
	mi := &file_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionPublishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionPublishedEvent) ProtoMessage() {}

func (x *PromotionPublishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionPublishedEvent.ProtoReflect.Descriptor instead.
func (*PromotionPublishedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *PromotionPublishedEvent) GetPromotionId() string {
	if x != nil {
		return x.PromotionId
	}
	return ""
}

func (x *PromotionPublishedEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PromotionPublishedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x02\n" +
	"\rEventEnvelope\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\rnew_promotion\x18\x03 \x01(\v2\x19.events.NewPromotionEventH\x00R\fnewPromotion\x12'\n" +
	"\x04vote\x18\x04 \x01(\v2\x11.events.VoteEventH\x00R\x04vote\x12R\n" +
	"\x13promotion_published\x18\x05 \x01(\v2\x1f.events.PromotionPublishedEventH\x00R\x12promotionPublishedB\t\n" +
	"\apayload\"t\n" +
	"\x11NewPromotionEvent\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\tR\vpromotionId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8b\x01\n" +
	"\tVoteEvent\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\tR\vpromotionId\x12\x1d\n" +
	"\n" +
	"vote_value\x18\x02 \x01(\x05R\tvoteValue\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"z\n" +
	"\x17PromotionPublishedEvent\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\tR\vpromotionId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB'Z%promocao/internal/models/proto/eventsb\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),           // 0: events.EventEnvelope
	(*NewPromotionEvent)(nil),       // 1: events.NewPromotionEvent
	(*VoteEvent)(nil),               // 2: events.VoteEvent
	(*PromotionPublishedEvent)(nil), // 3: events.PromotionPublishedEvent
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_proto_events_proto_depIdxs = []int32{
	4, // 0: events.EventEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: events.EventEnvelope.new_promotion:type_name -> events.NewPromotionEvent
	2, // 2: events.EventEnvelope.vote:type_name -> events.VoteEvent
	3, // 3: events.EventEnvelope.promotion_published:type_name -> events.PromotionPublishedEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	file_proto_events_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_NewPromotion)(nil),
		(*EventEnvelope_Vote)(nil),
		(*EventEnvelope_PromotionPublished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
